#!/usr/bin/env bash
set -euo pipefail

usage() {
  cat <<'EOF'
Usage:
  scripts/install_preview_global.sh ./mtplx-0.1.0rc1-py3-none-any.whl

Installs the private MTPLX preview wheel into ~/.mtplx/preview-venv and creates
a global `mtplx` launcher in ~/.local/bin. On Apple Silicon Homebrew installs,
it also writes /opt/homebrew/bin/mtplx when that directory is writable.

Environment:
  MTPLX_PYTHON=/path/to/python3.13
  MTPLX_PREVIEW_VENV=~/.mtplx/preview-venv
  MTPLX_USER_BIN=~/.local/bin
EOF
}

if [ "${1:-}" = "-h" ] || [ "${1:-}" = "--help" ]; then
  usage
  exit 0
fi

wheel="${1:-}"
if [ -z "$wheel" ]; then
  matches=()
  while IFS= read -r candidate; do
    matches+=("$candidate")
  done < <(find . dist -maxdepth 1 -name 'mtplx-*.whl' -type f 2>/dev/null | sort)
  if [ "${#matches[@]}" -eq 1 ]; then
    wheel="${matches[0]}"
  else
    usage
    echo
    echo "error: pass the MTPLX wheel path explicitly" >&2
    exit 2
  fi
fi

if [ ! -f "$wheel" ]; then
  echo "error: wheel not found: $wheel" >&2
  exit 2
fi

venv="${MTPLX_PREVIEW_VENV:-$HOME/.mtplx/preview-venv}"
user_bin="${MTPLX_USER_BIN:-$HOME/.local/bin}"
launcher="$user_bin/mtplx"
install_target="${wheel}[server]"
python_bin="${MTPLX_PYTHON:-}"

if [ -z "$python_bin" ]; then
  for candidate in python3.13 python3.12 python3.11 python3; do
    if command -v "$candidate" >/dev/null 2>&1; then
      python_bin="$(command -v "$candidate")"
      break
    fi
  done
fi

if [ -z "$python_bin" ]; then
  echo "error: could not find python3.11, python3.12, python3.13, or python3" >&2
  exit 2
fi

"$python_bin" -m venv "$venv"
"$venv/bin/python" -m pip install -U pip
"$venv/bin/python" -m pip install "$install_target"

mkdir -p "$user_bin"
cat > "$launcher" <<EOF
#!/usr/bin/env bash
# MTPLX preview launcher. Generated by scripts/install_preview_global.sh.
set -e

if [ -z "\${HF_HOME:-}" ] && [ -d "\$HOME/.cache/huggingface-mtplx" ]; then
  export HF_HOME="\$HOME/.cache/huggingface-mtplx"
fi

exec "$venv/bin/mtplx" "\$@"
EOF
chmod 755 "$launcher"

homebrew_launcher_installed=0
if [ "${MTPLX_SKIP_HOMEBREW_LAUNCHER:-0}" != "1" ] && [ -d /opt/homebrew/bin ] && [ -w /opt/homebrew/bin ]; then
  cp "$launcher" /opt/homebrew/bin/mtplx
  chmod 755 /opt/homebrew/bin/mtplx
  homebrew_launcher_installed=1
fi

path_snippet='
# MTPLX preview CLI
case ":$PATH:" in
  *":$HOME/.local/bin:"*) ;;
  *) export PATH="$HOME/.local/bin:$PATH" ;;
esac
'

for rcfile in "$HOME/.zprofile" "$HOME/.zshrc"; do
  touch "$rcfile"
  if ! grep -q 'MTPLX preview CLI' "$rcfile"; then
    printf '%s\n' "$path_snippet" >> "$rcfile"
  fi
done

"$launcher" --version
"$launcher" help >/dev/null

echo "MTPLX preview CLI installed:"
echo "  $launcher"
if [ "$homebrew_launcher_installed" -eq 1 ]; then
  echo "  /opt/homebrew/bin/mtplx"
fi
echo
echo "Open a new Terminal tab, or run: source ~/.zprofile && source ~/.zshrc"
